// Auto-generated by launcher.py - DO NOT EDIT MANUALLY
// Run 'python launcher.py --setup' to reconfigure

const MQTT_CONFIG = {
    host: 'Drews-MacBook-Pro.local',
    wsPort: 9001,
    get broker() {
        return `ws://${this.host}:${this.wsPort}`;
    }
};
